# Generated by Django 2.2.4 on 2020-10-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('raca', models.CharField(max_length=50)),
                ('nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
